{% set name = "legend-pygeom-optics" %}
{% set version = "0.13.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/legend_pygeom_optics-{{ version }}.tar.gz
  sha256: ffd7cba46f8b87668689d4707d661ac3c7b46519ba6656fcbbd3b86a16848e2c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.2
    - setuptools-scm >=7
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - numba
    - pint !=0.24.1
    - pyg4ometry
    - matplotlib-base
    - scipy
    - importlib_resources

test:
  imports:
    - legendoptics
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Optical properties of the LEGEND experiment
  home: https://github.com/legend-exp/legend-pygeom-optics
  license: GPL-3.0-only
  license_file: LICENSE
  doc_url: https://legend-pygeom-optics.readthedocs.io
  dev_url: https://github.com/legend-exp/legend-pygeom-optics

extra:
  recipe-maintainers:
    - gipert
    - ManuelHu
