schema_version: 1

context:
  name: legend-pygeom-optics
  version: "0.16.0"
  python_min: "3.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/legend_pygeom_optics-${{ version }}.tar.gz
  sha256: 600c387e449ced89da4165cb94c0f2cf86acceeab49a8439fdec4b2705d7ff50

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - legend-pygeom-optics = pygeomoptics.cli:optics_cli

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=77
    - setuptools-scm >=7
    - pip
  run:
    - python >=${{ python_min }}
    - numpy
    - numba
    - pint >=0.24.1
    - pyg4ometry
    - matplotlib-base
    - scipy
    - importlib_resources

tests:
  - python:
      imports:
        - legendoptics
        - pygeomoptics
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: Optical properties of the LEGEND experiment
  license: GPL-3.0-only
  license_file: LICENSE
  homepage: https://github.com/legend-exp/legend-pygeom-optics
  repository: https://github.com/legend-exp/legend-pygeom-optics
  documentation: https://legend-pygeom-optics.readthedocs.io

extra:
  recipe-maintainers:
    - gipert
    - ManuelHu
